// ===== СПИСОК ВСЕХ РАБОТ =====
// Чтобы добавить новую работу — просто скопируй одну строку и поменяй category/file/title.
// Ничего больше нигде трогать не нужно — секции, навигация и сетка соберутся сами.
//
// category — название секции (одинаковые category группируются вместе)
// file     — путь к файлу (положи сам gif/png в соответствующую папку assets/...)
// title    — подпись под картинкой (можно оставить пустой "")

const WORKS = [
  // ===== Best =====
  { category: "Best", file: "assets/Best/DW95jL.png", thumb: "thumbs/Best/DW95jL.jpg", title: "" },
  { category: "Best", file: "assets/Best/This creature shouldn’t exist  #horrortok #pixelart #horror #analoguehorror.mp4", thumb: "thumbs/Best/This creature shouldn’t exist  #horrortok #pixelart #horror #analoguehorror.jpg", title: "" },
  { category: "Best", file: "assets/Best/houses2.gif", thumb: "thumbs/Best/houses2.jpg", title: "" },
  { category: "Best", file: "assets/Best/zFchve9oU3Rl_rzgP3NkLqQKvCJEhM3HsF64XPRNzRtD6I8be_dM8Iu_4kuY8USq3Oq_8i5cAG2gep6-nmlMau4G.jpg", thumb: "thumbs/Best/zFchve9oU3Rl_rzgP3NkLqQKvCJEhM3HsF64XPRNzRtD6I8be_dM8Iu_4kuY8USq3Oq_8i5cAG2gep6-nmlMau4G.jpg", title: "" },
  { category: "Best", file: "assets/Best/4qeoB_.png", thumb: "thumbs/Best/4qeoB_.jpg", title: "" },
  { category: "Best", file: "assets/Best/Something’s Buzzing Inside NECK...🐝☠️.mp4", thumb: "thumbs/Best/Something’s Buzzing Inside NECK...🐝☠️.jpg", title: "" },
  { category: "Best", file: "assets/Best/finalboss.gif", thumb: "thumbs/Best/finalboss.jpg", title: "" },
  { category: "Best", file: "assets/Best/VJocXC.png", thumb: "thumbs/Best/VJocXC.jpg", title: "" },
  { category: "Best", file: "assets/Best/ufo.png", thumb: "thumbs/Best/ufo.jpg", title: "" },
  { category: "Best", file: "assets/Best/YQy3v4.png", thumb: "thumbs/Best/YQy3v4.jpg", title: "" },
  { category: "Best", file: "assets/Best/marrakesh.png", thumb: "thumbs/Best/marrakesh.jpg", title: "" },
  { category: "Best", file: "assets/Best/zombieallien1_big.gif", thumb: "thumbs/Best/zombieallien1_big.jpg", title: "" },
  { category: "Best", file: "assets/Best/elonmusk_specialA1.gif", thumb: "thumbs/Best/elonmusk_specialA1.jpg", title: "" },
  { category: "Best", file: "assets/Best/chest-Sheet-Sheet.gif", thumb: "thumbs/Best/chest-Sheet-Sheet.jpg", title: "" },
  { category: "Best", file: "assets/Best/scene.gif", thumb: "thumbs/Best/scene.jpg", title: "" },
  { category: "Best", file: "assets/Best/ACvUiv.png", thumb: "thumbs/Best/ACvUiv.jpg", title: "" },
  { category: "Best", file: "assets/Best/Anndy Lian_specialA.gif", thumb: "thumbs/Best/Anndy Lian_specialA.jpg", title: "" },
  { category: "Best", file: "assets/Best/44EbldA43guy_t8g4YdUJorikdJhHyONYdjNnx-Dq75NHVd6WecOI629LJ29dNG1Mcdl57x6Gvcl4H14hqZnXKI1.jpg", thumb: "thumbs/Best/44EbldA43guy_t8g4YdUJorikdJhHyONYdjNnx-Dq75NHVd6WecOI629LJ29dNG1Mcdl57x6Gvcl4H14hqZnXKI1.jpg", title: "" },
  { category: "Best", file: "assets/Best/2BA5HB.png", thumb: "thumbs/Best/2BA5HB.jpg", title: "" },
  { category: "Best", file: "assets/Best/Princess Rana - JumpWallFloor.gif", thumb: "thumbs/Best/Princess Rana - JumpWallFloor.jpg", title: "" },
  { category: "Best", file: "assets/Best/death2.1.gif", thumb: "thumbs/Best/death2.1.jpg", title: "" },
  { category: "Best", file: "assets/Best/runner.png", thumb: "thumbs/Best/runner.jpg", title: "" },
  { category: "Best", file: "assets/Best/all1.png", thumb: "thumbs/Best/all1.jpg", title: "" },

  // ===== Animations =====
  { category: "Animations", file: "assets/Animations/dash1_big.gif", thumb: "thumbs/Animations/dash1_big.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Doge_star.gif", thumb: "thumbs/Animations/Doge_star.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/cptareasleep1.gif", thumb: "thumbs/Animations/cptareasleep1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/zombieallien1_big.gif", thumb: "thumbs/Animations/zombieallien1_big.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/3.3.gif", thumb: "thumbs/Animations/3.3.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/5.gif", thumb: "thumbs/Animations/5.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/6.6.gif", thumb: "thumbs/Animations/6.6.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/7.7.gif", thumb: "thumbs/Animations/7.7.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/8.8.gif", thumb: "thumbs/Animations/8.8.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/14zBI2.gif", thumb: "thumbs/Animations/14zBI2.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/21s.gif", thumb: "thumbs/Animations/21s.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/33.gif", thumb: "thumbs/Animations/33.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/1123.gif", thumb: "thumbs/Animations/1123.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Anndy Lian_specialA.gif", thumb: "thumbs/Animations/Anndy Lian_specialA.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Aria big.gif", thumb: "thumbs/Animations/Aria big.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Atsuko Sato_specialB.gif", thumb: "thumbs/Animations/Atsuko Sato_specialB.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/attack.gif", thumb: "thumbs/Animations/attack.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/attack21.gif", thumb: "thumbs/Animations/attack21.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/breaddywalk.gif", thumb: "thumbs/Animations/breaddywalk.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/bubble.gif", thumb: "thumbs/Animations/bubble.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/bullscream.gif", thumb: "thumbs/Animations/bullscream.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/cA33T.gif", thumb: "thumbs/Animations/cA33T.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/cararmy1.gif", thumb: "thumbs/Animations/cararmy1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/catjumpstart.gif", thumb: "thumbs/Animations/catjumpstart.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/catsitjump.gif", thumb: "thumbs/Animations/catsitjump.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/changpengZhao_idle.gif", thumb: "thumbs/Animations/changpengZhao_idle.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/changpengZhao_specialA.gif", thumb: "thumbs/Animations/changpengZhao_specialA.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/characteridle1.gif", thumb: "thumbs/Animations/characteridle1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/characterwalk.gif", thumb: "thumbs/Animations/characterwalk.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/chest-Sheet-Sheet.gif", thumb: "thumbs/Animations/chest-Sheet-Sheet.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/clown.gif", thumb: "thumbs/Animations/clown.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/cptareaidle.gif", thumb: "thumbs/Animations/cptareaidle.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/cptareaidle1.gif", thumb: "thumbs/Animations/cptareaidle1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/cptareaplay1.gif", thumb: "thumbs/Animations/cptareaplay1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/crowidle.gif", thumb: "thumbs/Animations/crowidle.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/CW_Nohadown.gif", thumb: "thumbs/Animations/CW_Nohadown.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/DANTE.gif", thumb: "thumbs/Animations/DANTE.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/darkfairydeath1.gif", thumb: "thumbs/Animations/darkfairydeath1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/darkfairywalk1.gif", thumb: "thumbs/Animations/darkfairywalk1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/dash1_big.gif", thumb: "thumbs/Animations/dash1_big.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/death2.1.gif", thumb: "thumbs/Animations/death2.1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/dog_dash big.gif", thumb: "thumbs/Animations/dog_dash big.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Doge_star.gif", thumb: "thumbs/Animations/Doge_star.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/elonmusk_specialA1.gif", thumb: "thumbs/Animations/elonmusk_specialA1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/elonmusk_specialB.gif", thumb: "thumbs/Animations/elonmusk_specialB.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/elonmuskidle.gif", thumb: "thumbs/Animations/elonmuskidle.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/enemyknight_idle_attack.gif", thumb: "thumbs/Animations/enemyknight_idle_attack.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/er.gif", thumb: "thumbs/Animations/er.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/face.gif", thumb: "thumbs/Animations/face.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/FF.gif", thumb: "thumbs/Animations/FF.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/finalboss.gif", thumb: "thumbs/Animations/finalboss.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/finalbossdance.gif", thumb: "thumbs/Animations/finalbossdance.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/finalbossfinger.gif", thumb: "thumbs/Animations/finalbossfinger.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/finalbossflames.gif", thumb: "thumbs/Animations/finalbossflames.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/finalbosspuch2.gif", thumb: "thumbs/Animations/finalbosspuch2.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/fly.gif", thumb: "thumbs/Animations/fly.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/fsaafs.gif", thumb: "thumbs/Animations/fsaafs.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/girlheroidle.gif", thumb: "thumbs/Animations/girlheroidle.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/golemattack1.gif", thumb: "thumbs/Animations/golemattack1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/golemdeath1.gif", thumb: "thumbs/Animations/golemdeath1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/hero_idle.gif", thumb: "thumbs/Animations/hero_idle.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/heroidle.gif", thumb: "thumbs/Animations/heroidle.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Heroidle2.gif", thumb: "thumbs/Animations/Heroidle2.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/heroswordattack.gif", thumb: "thumbs/Animations/heroswordattack.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/heroswordodge.gif", thumb: "thumbs/Animations/heroswordodge.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/heroswordstand.gif", thumb: "thumbs/Animations/heroswordstand.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/hit2_fixed_big.gif", thumb: "thumbs/Animations/hit2_fixed_big.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/idle.gif", thumb: "thumbs/Animations/idle.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/iexVIY.gif", thumb: "thumbs/Animations/iexVIY.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/jump.gif", thumb: "thumbs/Animations/jump.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/kick.gif", thumb: "thumbs/Animations/kick.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/knight_idle_attack.gif", thumb: "thumbs/Animations/knight_idle_attack.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/knight_idle_deffence.gif", thumb: "thumbs/Animations/knight_idle_deffence.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/new trainer1.gif", thumb: "thumbs/Animations/new trainer1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/OctoMansword-Sheet.gif", thumb: "thumbs/Animations/OctoMansword-Sheet.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/PALADINBasicAttack.gif", thumb: "thumbs/Animations/PALADINBasicAttack.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/PALADINultimate.gif", thumb: "thumbs/Animations/PALADINultimate.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/pokemon1.gif", thumb: "thumbs/Animations/pokemon1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Rana - Jump _ Fall Animation (GIF).gif", thumb: "thumbs/Animations/Princess Rana - Jump _ Fall Animation (GIF).jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Rana - JumpFall-Sheet.gif", thumb: "thumbs/Animations/Princess Rana - JumpFall-Sheet.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Rana - JumpWallFloor.gif", thumb: "thumbs/Animations/Princess Rana - JumpWallFloor.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Rana - Run.gif", thumb: "thumbs/Animations/Princess Rana - Run.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Reina - Dash (GIF).gif", thumb: "thumbs/Animations/Princess Reina - Dash (GIF).jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Reina - Idle Animations (GIF).gif", thumb: "thumbs/Animations/Princess Reina - Idle Animations (GIF).jpg", title: "" },
  { category: "Animations", file: "assets/Animations/punch.gif", thumb: "thumbs/Animations/punch.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/RArAqS.gif", thumb: "thumbs/Animations/RArAqS.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/run.gif", thumb: "thumbs/Animations/run.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/run_big.gif", thumb: "thumbs/Animations/run_big.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/scene.gif", thumb: "thumbs/Animations/scene.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/shellopen.gif", thumb: "thumbs/Animations/shellopen.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/shootLaser.gif", thumb: "thumbs/Animations/shootLaser.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/skeleton_pharaon (1).gif", thumb: "thumbs/Animations/skeleton_pharaon (1).jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Sprite-0006.gif", thumb: "thumbs/Animations/Sprite-0006.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/Squirrelidle.gif", thumb: "thumbs/Animations/Squirrelidle.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/trainer 2.gif", thumb: "thumbs/Animations/trainer 2.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/trainer 3.gif", thumb: "thumbs/Animations/trainer 3.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/turtlewalk.gif", thumb: "thumbs/Animations/turtlewalk.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/VIKING1.gif", thumb: "thumbs/Animations/VIKING1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/VILAGER.gif", thumb: "thumbs/Animations/VILAGER.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/walk.gif", thumb: "thumbs/Animations/walk.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/wall_jump_big.gif", thumb: "thumbs/Animations/wall_jump_big.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/witchhide.gif", thumb: "thumbs/Animations/witchhide.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/witchjump.gif", thumb: "thumbs/Animations/witchjump.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/witchrun.gif", thumb: "thumbs/Animations/witchrun.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/womanattack1.gif", thumb: "thumbs/Animations/womanattack1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/womanwalk1.gif", thumb: "thumbs/Animations/womanwalk1.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/zombie.gif", thumb: "thumbs/Animations/zombie.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/zombie2.gif", thumb: "thumbs/Animations/zombie2.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/zombieallien1_big.gif", thumb: "thumbs/Animations/zombieallien1_big.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/zombieallien2_all.gif", thumb: "thumbs/Animations/zombieallien2_all.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/йцууцййуц.gif", thumb: "thumbs/Animations/йцууцййуц.jpg", title: "" },
  { category: "Animations", file: "assets/Animations/ф.gif", thumb: "thumbs/Animations/ф.jpg", title: "" },

    // ===== Portraits and illustrations =====
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/городдевушка1212211`111.png", thumb: "thumbs/portraits and illustrations/городдевушка1212211`111.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/Sprite-0Й003.png", thumb: "thumbs/portraits and illustrations/Sprite-0Й003.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/костер.png", thumb: "thumbs/portraits and illustrations/костер.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/poster113.png", thumb: "thumbs/portraits and illustrations/poster113.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/1ЙОЫ.png", thumb: "thumbs/portraits and illustrations/1ЙОЫ.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/ang1el.png", thumb: "thumbs/portraits and illustrations/ang1el.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/3.png", thumb: "thumbs/portraits and illustrations/3.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/asffasafsfas.png", thumb: "thumbs/portraits and illustrations/asffasafsfas.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/grassgirldtiys7.png", thumb: "thumbs/portraits and illustrations/grassgirldtiys7.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/LOOPHERO1.png", thumb: "thumbs/portraits and illustrations/LOOPHERO1.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/SPACEBRAINNNN1.png", thumb: "thumbs/portraits and illustrations/SPACEBRAINNNN1.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/pots.png", thumb: "thumbs/portraits and illustrations/pots.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/posterNEBO.png", thumb: "thumbs/portraits and illustrations/posterNEBO.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/izana.png", thumb: "thumbs/portraits and illustrations/izana.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/dsfdfsfds.png", thumb: "thumbs/portraits and illustrations/dsfdfsfds.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/dsfdfs.png", thumb: "thumbs/portraits and illustrations/dsfdfs.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/hinata.png", thumb: "thumbs/portraits and illustrations/hinata.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/HERO1EMOT1.png", thumb: "thumbs/portraits and illustrations/HERO1EMOT1.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/Sprite-0001.png", thumb: "thumbs/portraits and illustrations/Sprite-0001.jpg", title: "" },
  { category: "Portraits and illustrations", file: "assets/portraits and illustrations/makima11.png", thumb: "thumbs/portraits and illustrations/makima11.jpg", title: "" },

    // ===== Video =====
    // ВНИМАНИЕ: папки assets/Video/ пока НЕТ на GitHub — создай её и залей туда
    // эти файлы, иначе эта категория продолжит быть пустой (404 на все видео).
  { category: "Video", file: "assets/Video/Something’s Buzzing Inside NECK...🐝☠️.mp4", thumb: "thumbs/Video/Something’s Buzzing Inside NECK...🐝☠️.jpg", title: "" },
  { category: "Video", file: "assets/Video/This creature shouldn’t exist  #horrortok #pixelart #horror #analoguehorror.mp4", thumb: "thumbs/Video/This creature shouldn’t exist  #horrortok #pixelart #horror #analoguehorror.jpg", title: "" },
  { category: "Video", file: "assets/Video/The Science of Toxins_ A fatal drop.....💧☠️.mp4", thumb: "thumbs/Video/The Science of Toxins_ A fatal drop.....💧☠️.jpg", title: "" },
  { category: "Video", file: "assets/Video/1121(2).mp4", thumb: "thumbs/Video/1121(2).jpg", title: "" },
  { category: "Video", file: "assets/Video/A terrible tragedy happened because of this.mp4", thumb: "thumbs/Video/A terrible tragedy happened because of this.jpg", title: "" },
  { category: "Video", file: "assets/Video/He Have Eggs Inside...🪱🥚.mp4", thumb: "thumbs/Video/He Have Eggs Inside...🪱🥚.jpg", title: "" },
  { category: "Video", file: "assets/Video/He Dead - Fangs Already In...🤢🦷.mp4", thumb: "thumbs/Video/He Dead - Fangs Already In...🤢🦷.jpg", title: "" },
  { category: "Video", file: "assets/Video/This small creatures will kill you... #horrortok #pixelart #horror.mp4", thumb: "thumbs/Video/This small creatures will kill you... #horrortok #pixelart #horror.jpg", title: "" },
  { category: "Video", file: "assets/Video/True Detective was killed by this... #horror #music #kryptid.mp4", thumb: "thumbs/Video/True Detective was killed by this... #horror #music #kryptid.jpg", title: "" },
  { category: "Video", file: "assets/Video/v.gif", thumb: "thumbs/Video/v.jpg", title: "" },
  { category: "Video", file: "assets/Video/He wants to kill you and he's following you everywhere..mp4", thumb: "thumbs/Video/He wants to kill you and he"s following you everywhere..jpg", title: "" },
  
  // ===== Screenshots =====
  { category: "Screenshots", file: "assets/screenshots/44EbldA43guy_t8g4YdUJorikdJhHyONYdjNnx-Dq75NHVd6WecOI629LJ29dNG1Mcdl57x6Gvcl4H14hqZnXKI1.jpg", thumb: "thumbs/screenshots/44EbldA43guy_t8g4YdUJorikdJhHyONYdjNnx-Dq75NHVd6WecOI629LJ29dNG1Mcdl57x6Gvcl4H14hqZnXKI1.jpg", title: "" },
  { category: "Screenshots", file: "assets/screenshots/gfgfgfd.png", thumb: "thumbs/screenshots/gfgfgfd.jpg", title: "" },
  { category: "Screenshots", file: "assets/screenshots/zFchve9oU3Rl_rzgP3NkLqQKvCJEhM3HsF64XPRNzRtD6I8be_dM8Iu_4kuY8USq3Oq_8i5cAG2gep6-nmlMau4G.jpg", thumb: "thumbs/screenshots/zFchve9oU3Rl_rzgP3NkLqQKvCJEhM3HsF64XPRNzRtD6I8be_dM8Iu_4kuY8USq3Oq_8i5cAG2gep6-nmlMau4G.jpg", title: "" },
  { category: "Screenshots", file: "assets/screenshots/katscene1.png", thumb: "thumbs/screenshots/katscene1.jpg", title: "" },
  { category: "Screenshots", file: "assets/screenshots/marrakesh.png", thumb: "thumbs/screenshots/marrakesh.jpg", title: "" },
  { category: "Screenshots", file: "assets/screenshots/haZJpkrHxYQum4IXwNVx_B9IET7Nft3Ku_hrcFdIA2h3pjbS_CWTmddvl2XMrtnnLfGGdWT3gYkCUdWpHg-tIg5N.jpg", thumb: "thumbs/screenshots/haZJpkrHxYQum4IXwNVx_B9IET7Nft3Ku_hrcFdIA2h3pjbS_CWTmddvl2XMrtnnLfGGdWT3gYkCUdWpHg-tIg5N.jpg", title: "" },
  { category: "Screenshots", file: "assets/screenshots/-pPwApfM00A8QuaNnNxxgUSZO8DAtM85KAXv8HvZeSeB48s_VUgTPkLHtKFJIp9el6PQYfle8KDky3TNfhdJmbM3.jpg", thumb: "thumbs/screenshots/-pPwApfM00A8QuaNnNxxgUSZO8DAtM85KAXv8HvZeSeB48s_VUgTPkLHtKFJIp9el6PQYfle8KDky3TNfhdJmbM3.jpg", title: "" },
  
  // ===== Tilesets =====
  { category: "Tilesets", file: "assets/tilesets/1231-Recovered.png", thumb: "thumbs/tilesets/1231-Recovered.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/sprite111.png", thumb: "thumbs/tilesets/sprite111.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/12.png", thumb: "thumbs/tilesets/12.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/items.png", thumb: "thumbs/tilesets/items.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/32x32 first tileset.png", thumb: "thumbs/tilesets/32x32 first tileset.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/tiles.gif", thumb: "thumbs/tilesets/tiles.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/TILESET2.png", thumb: "thumbs/tilesets/TILESET2.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/1-Sheet.png", thumb: "thumbs/tilesets/1-Sheet.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/b0PnwC.png", thumb: "thumbs/tilesets/b0PnwC.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/cafe.png", thumb: "thumbs/tilesets/cafe.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/char.png", thumb: "thumbs/tilesets/char.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/concrete.png", thumb: "thumbs/tilesets/concrete.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/DEACORATIONS.png", thumb: "thumbs/tilesets/DEACORATIONS.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/erw.png", thumb: "thumbs/tilesets/erw.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/floor.png", thumb: "thumbs/tilesets/floor.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/Gold1.png", thumb: "thumbs/tilesets/Gold1.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/items.png", thumb: "thumbs/tilesets/items.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/items1.png", thumb: "thumbs/tilesets/items1.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/meteorite2.png", thumb: "thumbs/tilesets/meteorite2.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/meteorite6.png", thumb: "thumbs/tilesets/meteorite6.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/meteorite8.png", thumb: "thumbs/tilesets/meteorite8.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/mxkgHV.png", thumb: "thumbs/tilesets/mxkgHV.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/N1g7Ub.png", thumb: "thumbs/tilesets/N1g7Ub.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/oXFUu0.png", thumb: "thumbs/tilesets/oXFUu0.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/TABLE.png", thumb: "thumbs/tilesets/TABLE.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/TILESET.png", thumb: "thumbs/tilesets/TILESET.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/tileset111-Recovered.png", thumb: "thumbs/tilesets/tileset111-Recovered.jpg", title: "" },
  { category: "Tilesets", file: "assets/tilesets/tileset1111.png", thumb: "thumbs/tilesets/tileset1111.jpg", title: "" },
  
  

  
  // ===== Items =====
  { category: "Items", file: "assets/items/2BA5HB.png", thumb: "thumbs/items/2BA5HB.jpg", title: "" },
  { category: "Items", file: "assets/items/DW95jL.png", thumb: "thumbs/items/DW95jL.jpg", title: "" },
  { category: "Items", file: "assets/items/fgaN3f.png", thumb: "thumbs/items/fgaN3f.jpg", title: "" },
  { category: "Items", file: "assets/items/YQy3v4.png", thumb: "thumbs/items/YQy3v4.jpg", title: "" },
  { category: "Items", file: "assets/items/ver9.png", thumb: "thumbs/items/ver9.jpg", title: "" },
  { category: "Items", file: "assets/items/ver5.png", thumb: "thumbs/items/ver5.jpg", title: "" },
  { category: "Items", file: "assets/items/Copper2.png", thumb: "thumbs/items/Copper2.jpg", title: "" },
  { category: "Items", file: "assets/items/lerPp5.png", thumb: "thumbs/items/lerPp5.jpg", title: "" },
  { category: "Items", file: "assets/items/ver14.png", thumb: "thumbs/items/ver14.jpg", title: "" },
  { category: "Items", file: "assets/items/ver16.png", thumb: "thumbs/items/ver16.jpg", title: "" },

  

  // ===== Other =====
  { category: "Other", file: "assets/other/buttons_big.png", thumb: "thumbs/other/buttons_big.jpg", title: "" },
  { category: "Other", file: "assets/other/cards_1_big.png", thumb: "thumbs/other/cards_1_big.jpg", title: "" },
  { category: "Other", file: "assets/other/buttons1.png", thumb: "thumbs/other/buttons1.jpg", title: "" },
  { category: "Other", file: "assets/other/shampu_n.png", thumb: "thumbs/other/shampu_n.jpg", title: "" },
  { category: "Other", file: "assets/other/lizard rhino1.png", thumb: "thumbs/other/lizard rhino1.jpg", title: "" },
  { category: "Other", file: "assets/other/mollusk .png", thumb: "thumbs/other/mollusk .jpg", title: "" },
  { category: "Other", file: "assets/other/pter.png", thumb: "thumbs/other/pter.jpg", title: "" },
  { category: "Other", file: "assets/other/jackalope.png", thumb: "thumbs/other/jackalope.jpg", title: "" },
  { category: "Other", file: "assets/other/1.png", thumb: "thumbs/other/1.jpg", title: "" },
  { category: "Other", file: "assets/other/clubs2.png", thumb: "thumbs/other/clubs2.jpg", title: "" },
  
];
