// ===== СПИСОК ВСЕХ РАБОТ =====
// Чтобы добавить новую работу — просто скопируй одну строку и поменяй category/file/title.
// Ничего больше нигде трогать не нужно — секции, навигация и сетка соберутся сами.
//
// category — название секции (одинаковые category группируются вместе)
// file     — путь к файлу (положи сам gif/png в соответствующую папку assets/...)
// title    — подпись под картинкой (можно оставить пустой "")

const WORKS = [
  // ===== Best =====
  { category: "Best", file: "assets/Best/DW95jL.png", title: "" },
  { category: "Best", file: "assets/Best/This creature shouldn’t exist  #horrortok #pixelart #horror #analoguehorror.mp4", title: "" },
  { category: "Best", file: "assets/Best/houses2.gif", title: "" },
  { category: "Best", file: "assets/Best/zFchve9oU3Rl_rzgP3NkLqQKvCJEhM3HsF64XPRNzRtD6I8be_dM8Iu_4kuY8USq3Oq_8i5cAG2gep6-nmlMau4G.jpg", title: "" },
  { category: "Best", file: "assets/Best/4qeoB_.png", title: "" },
  { category: "Best", file: "assets/Best/Something’s Buzzing Inside NECK...🐝☠️.mp4", title: "" },
  { category: "Best", file: "assets/Best/finalboss.gif", title: "" },
  { category: "Best", file: "assets/Best/VJocXC.png", title: "" },
  { category: "Best", file: "assets/Best/ufo.png", title: "" },
  { category: "Best", file: "assets/Best/YQy3v4.png", title: "" },
  { category: "Best", file: "assets/Best/marrakesh.png", title: "" },
  { category: "Best", file: "assets/Best/zombieallien1_big.gif", title: "" },
  { category: "Best", file: "assets/Best/elonmusk_specialA1.gif", title: "" },
  { category: "Best", file: "assets/Best/chest-Sheet-Sheet.gif", title: "" },
  { category: "Best", file: "assets/Best/scene.gif", title: "" },
  { category: "Best", file: "assets/Best/ACvUiv.png", title: "" },
  { category: "Best", file: "assets/Best/Anndy Lian_specialA.gif", title: "" },
  { category: "Best", file: "assets/Best/44EbldA43guy_t8g4YdUJorikdJhHyONYdjNnx-Dq75NHVd6WecOI629LJ29dNG1Mcdl57x6Gvcl4H14hqZnXKI1.jpg", title: "" },
  { category: "Best", file: "assets/Best/2BA5HB.png", title: "" },
  { category: "Best", file: "assets/Best/Princess Rana - JumpWallFloor.gif", title: "" },
  { category: "Best", file: "assets/Best/death2.1.gif", title: "" },
  { category: "Best", file: "assets/Best/runner.png", title: "" },
  { category: "Best", file: "assets/Best/all1.png", title: "" },

  // ===== Animations =====
  { category: "Animations", file: "assets/Animations/dash1_big.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Doge_star.gif", title: "" },
  { category: "Animations", file: "assets/Animations/cptareasleep1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/zombieallien1_big.gif", title: "" },
  { category: "Animations", file: "assets/Animations/3.3.gif", title: "" },
  { category: "Animations", file: "assets/Animations/5.gif", title: "" },
  { category: "Animations", file: "assets/Animations/6.6.gif", title: "" },
  { category: "Animations", file: "assets/Animations/7.7.gif", title: "" },
  { category: "Animations", file: "assets/Animations/8.8.gif", title: "" },
  { category: "Animations", file: "assets/Animations/14zBI2.gif", title: "" },
  { category: "Animations", file: "assets/Animations/21s.gif", title: "" },
  { category: "Animations", file: "assets/Animations/33.gif", title: "" },
  { category: "Animations", file: "assets/Animations/1123.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Anndy Lian_specialA.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Aria big.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Atsuko Sato_specialB.gif", title: "" },
  { category: "Animations", file: "assets/Animations/attack.gif", title: "" },
  { category: "Animations", file: "assets/Animations/attack21.gif", title: "" },
  { category: "Animations", file: "assets/Animations/breaddywalk.gif", title: "" },
  { category: "Animations", file: "assets/Animations/bubble.gif", title: "" },
  { category: "Animations", file: "assets/Animations/bullscream.gif", title: "" },
  { category: "Animations", file: "assets/Animations/cA33T.gif", title: "" },
  { category: "Animations", file: "assets/Animations/cararmy1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/catjumpstart.gif", title: "" },
  { category: "Animations", file: "assets/Animations/catsitjump.gif", title: "" },
  { category: "Animations", file: "assets/Animations/changpengZhao_idle.gif", title: "" },
  { category: "Animations", file: "assets/Animations/changpengZhao_specialA.gif", title: "" },
  { category: "Animations", file: "assets/Animations/characteridle1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/characterwalk.gif", title: "" },
  { category: "Animations", file: "assets/Animations/chest-Sheet-Sheet.gif", title: "" },
  { category: "Animations", file: "assets/Animations/clown.gif", title: "" },
  { category: "Animations", file: "assets/Animations/cptareaidle.gif", title: "" },
  { category: "Animations", file: "assets/Animations/cptareaidle1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/cptareaplay1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/crowidle.gif", title: "" },
  { category: "Animations", file: "assets/Animations/CW_Nohadown.gif", title: "" },
  { category: "Animations", file: "assets/Animations/DANTE.gif", title: "" },
  { category: "Animations", file: "assets/Animations/darkfairydeath1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/darkfairywalk1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/dash1_big.gif", title: "" },
  { category: "Animations", file: "assets/Animations/death2.1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/dog_dash big.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Doge_star.gif", title: "" },
  { category: "Animations", file: "assets/Animations/elonmusk_specialA1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/elonmusk_specialB.gif", title: "" },
  { category: "Animations", file: "assets/Animations/elonmuskidle.gif", title: "" },
  { category: "Animations", file: "assets/Animations/enemyknight_idle_attack.gif", title: "" },
  { category: "Animations", file: "assets/Animations/er.gif", title: "" },
  { category: "Animations", file: "assets/Animations/face.gif", title: "" },
  { category: "Animations", file: "assets/Animations/FF.gif", title: "" },
  { category: "Animations", file: "assets/Animations/finalboss.gif", title: "" },
  { category: "Animations", file: "assets/Animations/finalbossdance.gif", title: "" },
  { category: "Animations", file: "assets/Animations/finalbossfinger.gif", title: "" },
  { category: "Animations", file: "assets/Animations/finalbossflames.gif", title: "" },
  { category: "Animations", file: "assets/Animations/finalbosspuch2.gif", title: "" },
  { category: "Animations", file: "assets/Animations/fly.gif", title: "" },
  { category: "Animations", file: "assets/Animations/fsaafs.gif", title: "" },
  { category: "Animations", file: "assets/Animations/girlheroidle.gif", title: "" },
  { category: "Animations", file: "assets/Animations/golemattack1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/golemdeath1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/hero_idle.gif", title: "" },
  { category: "Animations", file: "assets/Animations/heroidle.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Heroidle2.gif", title: "" },
  { category: "Animations", file: "assets/Animations/heroswordattack.gif", title: "" },
  { category: "Animations", file: "assets/Animations/heroswordodge.gif", title: "" },
  { category: "Animations", file: "assets/Animations/heroswordstand.gif", title: "" },
  { category: "Animations", file: "assets/Animations/hit2_fixed_big.gif", title: "" },
  { category: "Animations", file: "assets/Animations/idle.gif", title: "" },
  { category: "Animations", file: "assets/Animations/iexVIY.gif", title: "" },
  { category: "Animations", file: "assets/Animations/jump.gif", title: "" },
  { category: "Animations", file: "assets/Animations/kick.gif", title: "" },
  { category: "Animations", file: "assets/Animations/knight_idle_attack.gif", title: "" },
  { category: "Animations", file: "assets/Animations/knight_idle_deffence.gif", title: "" },
  { category: "Animations", file: "assets/Animations/new trainer1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/OctoMansword-Sheet.gif", title: "" },
  { category: "Animations", file: "assets/Animations/PALADINBasicAttack.gif", title: "" },
  { category: "Animations", file: "assets/Animations/PALADINultimate.gif", title: "" },
  { category: "Animations", file: "assets/Animations/pokemon1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Rana - Jump _ Fall Animation (GIF).gif", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Rana - JumpFall-Sheet.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Rana - JumpWallFloor.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Rana - Run.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Reina - Dash (GIF).gif", title: "" },
  { category: "Animations", file: "assets/Animations/Princess Reina - Idle Animations (GIF).gif", title: "" },
  { category: "Animations", file: "assets/Animations/punch.gif", title: "" },
  { category: "Animations", file: "assets/Animations/RArAqS.gif", title: "" },
  { category: "Animations", file: "assets/Animations/run.gif", title: "" },
  { category: "Animations", file: "assets/Animations/run_big.gif", title: "" },
  { category: "Animations", file: "assets/Animations/scene.gif", title: "" },
  { category: "Animations", file: "assets/Animations/shellopen.gif", title: "" },
  { category: "Animations", file: "assets/Animations/shootLaser.gif", title: "" },
  { category: "Animations", file: "assets/Animations/skeleton_pharaon (1).gif", title: "" },
  { category: "Animations", file: "assets/Animations/Sprite-0006.gif", title: "" },
  { category: "Animations", file: "assets/Animations/Squirrelidle.gif", title: "" },
  { category: "Animations", file: "assets/Animations/trainer 2.gif", title: "" },
  { category: "Animations", file: "assets/Animations/trainer 3.gif", title: "" },
  { category: "Animations", file: "assets/Animations/turtlewalk.gif", title: "" },
  { category: "Animations", file: "assets/Animations/VIKING1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/VILAGER.gif", title: "" },
  { category: "Animations", file: "assets/Animations/walk.gif", title: "" },
  { category: "Animations", file: "assets/Animations/wall_jump_big.gif", title: "" },
  { category: "Animations", file: "assets/Animations/witchhide.gif", title: "" },
  { category: "Animations", file: "assets/Animations/witchjump.gif", title: "" },
  { category: "Animations", file: "assets/Animations/witchrun.gif", title: "" },
  { category: "Animations", file: "assets/Animations/womanattack1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/womanwalk1.gif", title: "" },
  { category: "Animations", file: "assets/Animations/zombie.gif", title: "" },
  { category: "Animations", file: "assets/Animations/zombie2.gif", title: "" },
  { category: "Animations", file: "assets/Animations/zombieallien1_big.gif", title: "" },
  { category: "Animations", file: "assets/Animations/zombieallien2_all.gif", title: "" },
  { category: "Animations", file: "assets/Animations/йцууцййуц.gif", title: "" },
  { category: "Animations", file: "assets/Animations/ф.gif", title: "" },

    // ===== Portraits and illustrations =====
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/городдевушка1212211`111.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/Sprite-0Й003.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/костер.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/poster113.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/1ЙОЫ.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/ang1el.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/3.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/asffasafsfas.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/grassgirldtiys7.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/LOOPHERO1.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/SPACEBRAINNNN1.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/pots.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/posterNEBO.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/izana.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/dsfdfsfds.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/dsfdfs.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/hinata.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/HERO1EMOT1.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/Sprite-0001.png", title: "" },
  { category: "Portraits and illustrations", file: "assets/Portraits and illustrations/makima11.png", title: "" },

    // ===== Video =====
  { category: "Video", file: "assets/Video/Something’s Buzzing Inside NECK...🐝☠️.mp4", title: "" },
  { category: "Video", file: "assets/Video/This creature shouldn’t exist  #horrortok #pixelart #horror #analoguehorror.mp4", title: "" },
  { category: "Video", file: "assets/Video/The Science of Toxins_ A fatal drop.....💧☠️.mp4", title: "" },
  { category: "Video", file: "assets/Video/1121(2).mp4", title: "" },
  { category: "Video", file: "assets/Video/A terrible tragedy happened because of this.mp4", title: "" },
  { category: "Video", file: "assets/Video/He Have Eggs Inside...🪱🥚.mp4", title: "" },
  { category: "Video", file: "assets/Video/He Dead - Fangs Already In...🤢🦷.mp4", title: "" },
  { category: "Video", file: "assets/Video/This small creatures will kill you... #horrortok #pixelart #horror.mp4", title: "" },
  { category: "Video", file: "assets/Video/True Detective was killed by this... #horror #music #kryptid.mp4", title: "" },
  { category: "Video", file: "assets/Video/v.gif", title: "" },
  { category: "Video", file: "assets/Video/He wants to kill you and he's following you everywhere..mp4", title: "" },
  
  // ===== Screenshots =====
  { category: "Screenshots", file: "assets/Screenshots/44EbldA43guy_t8g4YdUJorikdJhHyONYdjNnx-Dq75NHVd6WecOI629LJ29dNG1Mcdl57x6Gvcl4H14hqZnXKI1.jpg", title: "" },
  { category: "Screenshots", file: "assets/Screenshots/gfgfgfd.png", title: "" },
  { category: "Screenshots", file: "assets/Screenshots/zFchve9oU3Rl_rzgP3NkLqQKvCJEhM3HsF64XPRNzRtD6I8be_dM8Iu_4kuY8USq3Oq_8i5cAG2gep6-nmlMau4G.jpg", title: "" },
  { category: "Screenshots", file: "assets/Screenshots/katscene1.png", title: "" },
  { category: "Screenshots", file: "assets/Screenshots/marrakesh.png", title: "" },
  { category: "Screenshots", file: "assets/Screenshots/haZJpkrHxYQum4IXwNVx_B9IET7Nft3Ku_hrcFdIA2h3pjbS_CWTmddvl2XMrtnnLfGGdWT3gYkCUdWpHg-tIg5N.jpg", title: "" },
  { category: "Screenshots", file: "assets/Screenshots/-pPwApfM00A8QuaNnNxxgUSZO8DAtM85KAXv8HvZeSeB48s_VUgTPkLHtKFJIp9el6PQYfle8KDky3TNfhdJmbM3.jpg", title: "" },
  
  // ===== Tilesets =====
  { category: "Tilesets", file: "assets/Tilesets/1231-Recovered.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/sprite111.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/12.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/items.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/32x32 first tileset.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/tiles.gif", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/TILESET2.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/1-Sheet.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/b0PnwC.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/cafe.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/char.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/concrete.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/DEACORATIONS.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/erw.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/floor.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/Gold1.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/items.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/items1.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/meteorite2.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/meteorite6.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/meteorite8.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/mxkgHV.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/N1g7Ub.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/oXFUu0.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/TABLE.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/TILESET.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/tileset111-Recovered.png", title: "" },
  { category: "Tilesets", file: "assets/Tilesets/tileset1111.png", title: "" },
  
  

  
  // ===== Items =====
  { category: "Items", file: "assets/Items/2BA5HB.png", title: "" },
  { category: "Items", file: "assets/Items/DW95jL.png", title: "" },
  { category: "Items", file: "assets/Items/fgaN3f.png", title: "" },
  { category: "Items", file: "assets/Items/YQy3v4.png", title: "" },
  { category: "Items", file: "assets/Items/ver9.png", title: "" },
  { category: "Items", file: "assets/Items/ver5.png", title: "" },
  { category: "Items", file: "assets/Items/Copper2.png", title: "" },
  { category: "Items", file: "assets/Items/lerPp5.png", title: "" },
  { category: "Items", file: "assets/Items/ver14.png", title: "" },
  { category: "Items", file: "assets/Items/ver16.png", title: "" },

  

  // ===== Other =====
  { category: "Other", file: "assets/Other/buttons_big.png", title: "" },
  { category: "Other", file: "assets/Other/cards_1_big.png", title: "" },
  { category: "Other", file: "assets/Other/buttons1.png", title: "" },
  { category: "Other", file: "assets/Other/shampu_n.png", title: "" },
  { category: "Other", file: "assets/Other/lizard rhino1.png", title: "" },
  { category: "Other", file: "assets/Other/mollusk .png", title: "" },
  { category: "Other", file: "assets/Other/pter.png", title: "" },
  { category: "Other", file: "assets/Other/jackalope.png", title: "" },
  { category: "Other", file: "assets/Other/1.png", title: "" },
  { category: "Other", file: "assets/Other/clubs2.png", title: "" },
  
];
